### ISSUE TITLE
Движок имеет ограничение на количество include файлов в Less

### ISSUE THREAD

**Issue by sashko2000** [Taritsyn/MsieJavaScriptEngine#12]

**Comment by Taritsyn** [comment]
Приведите конкретный пример.

**Comment by sashko2000** [comment]
[http://eluxr.com/assets.zip](http://eluxr.com/assets.zip)
Здесь файл skin\default_skin\less\theme.less 
При компиляции выдает пустой результат.
Методом исключения понял, что проблема в количестве файлов. V8 отработало нормально.

**Comment by Taritsyn** [comment]
Кроме [JavaScriptEngineSwitcher.V8](http://nuget.org/packages/JavaScriptEngineSwitcher.V8) и [JavaScriptEngineSwitcher.Vroom](http://nuget.org/packages/JavaScriptEngineSwitcher.Vroom) ни один из других модулей [JavaScript Engine Switcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher) не смог обработать эти стили. Возможно, что у вас где-то есть `@import`, который приводит к бесконечному циклу.

В любом случае, вы пытаетесь обработать с помощью [BundleTransformer.Less](http://www.nuget.org/packages/BundleTransformer.Less/) слишком большой объем кода, и таким образом просто убиваете свой веб-сервер. Я бы на вашем месте задумался о переходе на [Grunt](http://gruntjs.com/), [Gulp](http://gulpjs.com/) или [Webpack](https://webpack.js.org/).

**Comment by sashko2000** [comment]
Спасибо,что посмотрели. Там именно проблема в количестве файлов. А стили мне достались от темплейта. ;-)

**Comment by Taritsyn** [comment]
Скорее всего, проблема не в количестве файлов, а в перерасходе памяти или превышении предельного размера стека. Это сложно определить, когда используется виртуальная файловая система. Фактически при обработке каждого `@import`а BundleTransformer.Less открывает канал обмена данными между управляемым и неуправляемым кодом, что приводит к дополнительному расходу памяти.

В любом случае, помочь с этой проблемой вам не смогу. У вас есть 4 варианта решения проблемы:

1. Продолжать использовать V8, потому что это самый высокопроизводительный JS-движок в мире.
2. Закомментировать ненужные `@import`ы.
3. Попробовать вместо BundleTransformer.Less использовать [dotless](https://github.com/dotless/dotless).
4. Проводить трансляцию LESS-файлов на этапе сборки проекта.

**Comment by sashko2000** [comment]
Еще раз спасибо.
