### ISSUE TITLE
Anonymous Host Objects

### ISSUE THREAD

**Issue by rhett-thompson** [Taritsyn/MsieJavaScriptEngine#14]
It doesn't look like you can embed anonymous objects with EmbedHostObject at present.

Is the best way to do this to serialize the object to json and include in the js being executed?

Thanks.

**Comment by Taritsyn** [comment]
Hello, Rhett!

Anonymous types differ little from other .NET types. In my opinion there is only one significant difference: “Properties of anonymous type are read only and they cannot be set”.

> It doesn't look like you can embed anonymous objects with EmbedHostObject at present.

It works for me. I even wrote a [unit test to verify this](https://github.com/Taritsyn/MsieJavaScriptEngine/commit/1b2c589733508687ae79ce1ed0fbfa78cd018d4b). But it is worth noting, that current version of the `EmbedHostObject` method does not support projection of collection types.

> Is the best way to do this to serialize the object to json and include in the js being executed?

`EmbedHostObject` method it is recommended to use for embedding of active objects (for example, objects with methods, that you will call from the script). If you just need to pass data to the script, then it is better to use JSON serialization (this will require less resources).

I also recommend you to see a [real example of using the `EmbedHostObject` method and JSON serialization](https://github.com/Taritsyn/BundleTransformer/blob/master/src/BundleTransformer.TypeScript/Internal/TypeScriptCompiler.cs).
