### ISSUE TITLE
What's the purpose of using MsieJavaScriptEngine?

### ISSUE THREAD

**Issue by Legends** [Taritsyn/MsieJavaScriptEngine#15]
What's the purpose of using MsieJavaScriptEngine?
When would someone use it, use case?

**Comment by Taritsyn** [comment]
Hello!

Have you read the [README.md](https://github.com/Taritsyn/MsieJavaScriptEngine/blob/master/README.md)?

**Comment by Legends** [comment]
Yes, I have. A JavaScript Engine is used in browsers for executing JS. 
But what do I do with the MsieJavaScriptEngine on the server when using C#?

I mean, your example shows a string expression which calculates the value, but what else?

**Comment by Taritsyn** [comment]
> Yes, I have. A JavaScript Engine is used in browsers for executing JS.
> But what do I do with the MsieJavaScriptEngine on the server when using C#?

Such engines are used to execute the code of Node.js libraries (for example, LESS, CoffeeScript, TypeScript and React) from .NET.

In most projects the MSIE JavaScript Engine is used via the [JavaScript Engine Switcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher) library. Good examples of such use are the following libraries: [Bundle Transformer](https://github.com/Taritsyn/BundleTransformer) and [ReactJS.NET](https://github.com/reactjs/React.NET).

> I mean, your example shows a string expression which calculates the value, but what else?

As examples, you can see the code of [unit tests](https://github.com/Taritsyn/MsieJavaScriptEngine/tree/master/test).
