### ISSUE TITLE
Binaries in source folders

### ISSUE THREAD

**Issue by kunalspathak** [Taritsyn/MsieJavaScriptEngine#4]
Is there any reason why you have nuget.exe in .nuget and Nuget folders?

**Comment by Taritsyn** [comment]
Hello, Kunal!

This is necessary to automatically restore of NuGet packages.

**Comment by SimonCropp** [comment]
not since later versions of VS 2013 and all versions of VS2015

and all build servers support a prebuild step to restore packages

**Comment by Taritsyn** [comment]
I save compatibility with Visual Studio 2012.

Redundant nuget.exe file was deleted.

**Comment by kunalspathak** [comment]
Sounds good @Taritsyn .  Does it matter that it has to be specific version of nuget.exe to work with VS 2012? If not, you can just add a pre-requisite in readme.md to download nuget.exe instead of having it checked in.

**Comment by Taritsyn** [comment]
Hello, Kunal!

Actually, I did it by example of Mads Kristensen's repositories: [WebEssentials2013](https://github.com/madskristensen/WebEssentials2013) and [StaticWebHelper](https://github.com/madskristensen/StaticWebHelper).
