### ISSUE TITLE
Pass in JavaScript object reference to CallFunction

### ISSUE THREAD

**Issue by ctaggart** [Taritsyn/MsieJavaScriptEngine#5]
I want to pass a JavaScript object reference in as an argument in `CallFunction`. Do you think this might be possible to do? I currently get this exception when using this code (from https://github.com/ctaggart/TsAst/issues/5):

![image](https://cloud.githubusercontent.com/assets/80104/12012242/03bd2e54-aca1-11e5-9daf-a4b4257a1305.png)

``` fs
module Taser.Chakra

open MsieJavaScriptEngine

let main() =
    use jse = 
        new MsieJsEngine(
            JsEngineSettings(
                EngineMode = JsEngineMode.ChakraEdgeJsRt,
                UseEcmaScript5Polyfill = false,
                UseJson2Library = false))

    jse.Execute
        """
        function add(num1, num2) {
			return (num1 + num2);
		}
        """

    let a = jse.Evaluate "add(7, 9);" 
    printfn "a: %A" a // a: 16.0

    let b = jse.Evaluate<int> "add(7, 9);"
    printfn "b: %A" b // b: 16

    let i = jse.CallFunction<int>("add", 7, 9)
    printfn "i: %A" i // i: 16

    jse.ExecuteFile @"C:\ts\TsAst\node_modules\typescript\lib\typescriptServices.js"
    let node = jse.Evaluate @"ts.createNode(1);"
    printfn "node: %A" node // node: System.__ComObject

    jse.Execute "function getKind(node){ return node.kind; }"
    let kind = jse.CallFunction("getKind", node);
    // Exception: One of the function parameters 'getKind' has a type `System.__ComObject`, which is not supported.
    printfn "kind: %A" kind
```

**Comment by ctaggart** [comment]
This definitely looks possible using the lower level Edge API. [MapToHostType](https://github.com/Taritsyn/MsieJavaScriptEngine/blob/master/src/MsieJavaScriptEngine/JsRt/Edge/ChakraEdgeJsRtJsEngine.cs#L213) is converting the `EdgeJsValue`, but I want it to hold onto it so that it can be passed into [JsCallFunction](https://github.com/Taritsyn/MsieJavaScriptEngine/blob/master/src/MsieJavaScriptEngine/JsRt/Edge/EdgeNativeMethods.cs#L219) somehow. I'll see what I can hack together.

**Comment by Taritsyn** [comment]
Hello, Cameron!

> I want to pass a JavaScript object reference in as an argument in  CallFunction . Do you think this might be possible to do?

Answer to your question is contained in the text of error message. In addition, the documentation is clearly written:

The supported .NET types are as follows:
 * `MsieJavaScriptEngine.Undefined`
 * `System.Boolean`
 * `System.Int32` 
 * `System.Double`
 * `System.String`

> This definitely looks possible using the lower level Edge API. MapToHostType is converting the  EdgeJsValue , but I want it to hold onto it so that it can be passed into JsCallFunction somehow. I'll see what I can hack together.

You can directly use the JsRT version of Chakra. See the following repositories: [Chakra Sample Hosts](https://github.com/panopticoncentral/chakra-host) and [Chakra-Samples](https://github.com/Microsoft/Chakra-Samples). Or wait for the release of [ChakraCore](https://blogs.windows.com/msedgedev/2015/12/05/open-source-chakra-core/).
