### ISSUE TITLE
How to get data back from JS to C#?

### ISSUE THREAD

**Issue by andreykorolev** [Taritsyn/MsieJavaScriptEngine#8]
I have executed the following script:
`
var obj = { n: 123, s: 'str' }
`
GetVariableValue("obj") has returned COM Object.

How can I get data from JS to C# as ExpandoObject or Dictionary<string, object>?

**Comment by Taritsyn** [comment]
Hello, Andrey!

In no way. Supports only primitive types.

But it is possible serialize the object to a string:

```js
JSON.stringify(obj);
```

And then deserialize the string result by using the [Json.NET](http://www.newtonsoft.com/json) library:

```csharp
var json = JObject.Parse(result);
…
```

As an example, I recommend you see the source code of the [BundleTransformer.Less](http://bundletransformer.codeplex.com/SourceControl/latest#BundleTransformer.Less/Internal/LessCompiler.cs). There used the [JavaScript Engine Switcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher), but it has a very similar API.
